const labelMap = {
  about: '关于',
  //intro
  'what is fuel': '什么是Fuel',
  quickstart: '快速开始',
  glossary: '术语表',
  //指南
  guides: '指南',
  'contract quickstart': '智能合约快速入门',
  'frontend quickstart': '前端快速入门',
  'counter dapp': '计数器dapp',
  'running a node': '运行节点',
  'migration guide': '迁移指引',
  'intro to sway': '面向JS开发者的Sway语言简介',

  //sway
  introduction: '介绍',
  'getting started': '入门',
  'fuel toolchain': 'Fuel工具链',
  'forc project': 'forc工程',
  'standard library': '标准库',
  'sway standards': 'Sway标准',

  examples: '示例',
  'wallet smart contract': '钱包智能合约',
  'liquidity pool': '流动性池',
  'sway applications': 'Sway 应用',

  'sway program types': 'Sway 程序类型',
  'smart contracts': '智能合约',
  libraries: '库(Libraries)',
  scripts: '脚本(Scripts)',
  predicates: '断言(Predicates)',

  basics: '基础',
  variables: '变量',
  'built in types': '内置类型',
  'commonly used library types': '常用的库类型',
  'blockchain types': '区块链类型',
  'converting types': '类型转换',
  functions: '函数',
  'structs tuples and enums': '结构体、元组和枚举',
  'methods and associated functions': '方法和关联函数',
  constants: '常量',
  'comments and logging': '注释和日志',
  'control flow': '控制流',

  'blockchain development': '区块链开发',
  'hashing and cryptography': '哈希和加密',
  storage: '存储',
  purity: '纯度',
  identifiers: '标识符',
  'native assets': '原生资产',
  'access control': '访问控制',
  'calling contracts': '调用合约',
  'external code': '外部代码执行',

  advanced: '高级概念',
  'advanced types': '高级类型',
  'advanced storage': '高级存储',
  'generic types': '泛型类型',
  traits: '特性(traits)',
  'associated types': '关联类型',
  'generics and trait constraints': '泛型和特质约束',
  assembly: '内联汇编',
  'never type': 'Never 类型',

  'common collections': '常见集合',
  vec: '向量',
  'storage vec': '存储向量',
  'storage map': '存储映射',

  testing: '测试',
  'unit testing': '单元测试',
  'testing with rust': '使用rust测试',

  debugging: '调试',
  'debugging with cli': '使用CLI调试',
  'debugging with ide': '使用ide调试',

  installation: '安装',
  features: '功能特性',
  troubleshooting: '故障排除',

  reference: '参考',
  'sway libs': 'Sway 库',
  'compiler intrinsics': '编译器内联函数',
  attributes: '属性',
  'style guide': '风格指南',
  'known issues and workarounds': '已知问题和解决方法',
  'solidity differences': '与 Solidity 的差异',
  'rust differences': '与 Rust 的不同之处',
  'contributing to sway': 'Sway 贡献指南',
  keywords: 'keywords关键字',

  //sway-libs
  'running tests': '运行测试',
  asset: '资产库',
  base: '基本功能',
  supply: '供应功能',
  metadata: '元数据功能',

  admin: 'Admin库',
  ownership: 'Ownership库',
  pausable: 'Pausable库',
  reentrancy: '重入保护库',
  bytecode: '字节码库',
  merkle: 'Merkle 库',
  'fixed point': '固定小数点数库',
  'signed integers': '有符号整数库',
  queue: '队列库',

  //ts sdk
  'connecting to a local node': '连接到本地节点',
  'connecting to testnet': '连接到测试网',
  'further resources': '更多资源',
  usage: '用法',
  'creating a fuel dapp': '创建 Fuel Dapp',
  'deploying a dapp to testnet': '将 Dapp 部署到测试网络',
  options: '选项',
  'abi typegen': 'ABI 类型生成器',
  commands: '命令',
  'config file': '配置文件',
  'generating types': '类型生成',
  'using generated types': '使用生成的类型',
  provider: '提供者',
  'provider options': '提供者选项',
  'querying the chain': '查询链上信息',
  wallets: '钱包',
  'instantiating wallets': '实例化钱包',
  'private keys': '私钥钱包',
  'mnemonic wallet': '助记词钱包',
  'encrypting and decrypting': '加密和解密',
  'checking balances': '检查余额',
  'wallet transferring': '钱包转账',
  signing: '签名',
  connectors: '连接器',
  'wallet manager': '钱包管理器',
  'locking and unlocking': '锁定和解锁',
  'test wallets': '测试钱包',
  contracts: '合约',
  methods: '方法',
  'call parameters': '调用参数',
  'contract balance': '合约余额',
  'cost estimation': '估算交易成本',
  'dependency estimation': '依赖估算',
  'variable outputs': '可变输出',
  logs: '日志',
  'inter contract calls': '合约间调用',
  'multi contract calls': '多合约调用',
  'using different wallets': '使用不同的钱包',
  'transferring assets': '资产转移',
  'deploying contracts': '部署合约',
  'storage slots': '存储槽位',
  'configurable constants': '可配置常量',
  'managing deployed contracts': '管理部署的合约',
  'understanding the fuelvm binary file': '理解 FuelVM 二进制文件',
  'instantiating a script': '实例化脚本',
  'running scripts': '运行脚本',
  'custom script call': '调用自定义脚本',
  'instantiating a predicate': '实例化断言',
  'send and spend funds from predicates': '从断言发送和花费资金',
  transactions: '交易',
  'transaction parameters': '交易参数',
  'transaction policies': '交易策略',
  'transaction request': '交易请求',
  'transaction response': '交易响应',
  utilities: '实用工具',
  'date conversion': '日期转换',
  'address conversion': '地址转换',
  'unit conversion': '单位转换',
  'deposit and withdraw': '存款和取款',
  'wallet sdk and react hooks': '钱包 SDK 和 React Hooks',
  'custom transactions': '自定义交易',
  'custom transactions from contract calls': '通过合约调用创建自定义交易',
  'transactions with multiple signers': '多签名者的交易',
  'graphql integration': 'GraphQL 集成',
  'setting up a custom chain': '设置自定义链',
  'testing in ts': '在 TS 中进行测试',
  'tweaking the blockchain': '生成区块',
  types: '类型',
  'asset id': 'AssetId',
  errors: 'errors',
  'error codes': 'error codes',
  api: 'api',
  account: 'account',
  assembletransactionsummaryparams: 'assembletransactionsummaryparams',
  basetransactionrequest: 'basetransactionrequest',
  basewalletunlocked: 'basewalletunlocked',
  calculategasfeeparams: 'calculategasfeeparams',
  createtransactionrequest: 'createtransactionrequest',
  fuel: 'fuel',
  fuelconnector: 'fuelconnector',
  fuelconnectoreventtypes: 'fuelconnectoreventtypes',
  fuelconnectormethods: 'fuelconnectormethods',
  generateoptions: 'generateoptions',
  gettransactionsummaryfromrequestparams:
    'gettransactionsummaryfromrequestparams',
  gettransactionssummariesparams: 'gettransactionssummariesparams',
  gettransactionssummariesreturns: 'gettransactionssummariesreturns',
  gettransferoperationsparams: 'gettransferoperationsparams',
  hdwallet: 'hdwallet',
  iaddamounttoassetparams: 'iaddamounttoassetparams',
  igetmaxgasparams: 'igetmaxgasparams',
  igetmingasparams: 'igetmingasparams',
  language: 'language',
  localstorage: 'localstorage',
  memorystorage: 'memorystorage',
  mintedasset: 'mintedasset',
  mnemonic: 'mnemonic',
  mnemonicvault: 'mnemonicvault',
  mnemonicvaultoptions: 'mnemonicvaultoptions',
  pkvaultoptions: 'pkvaultoptions',
  predicate: 'predicate',
  privatekeyvault: 'privatekeyvault',
  scripttransactionrequest: 'scripttransactionrequest',
  signer: 'signer',
  storageabstract: 'storageabstract',
  targetobject: 'targetobject',
  transactionresponse: 'transactionresponse',
  transactiontype: 'transactiontype',
  vault: 'vault',
  wallet: 'wallet',
  walletlocked: 'walletlocked',
  walletmanager: 'walletmanager',
  walletmanagerstate: 'walletmanagerstate',
  walletunlocked: 'walletunlocked',
  contractfactory: 'contractfactory',
  interfaces: 'interfaces',
  abstractaccount: 'abstractaccount',
  abstractaddress: 'abstractaddress',
  abstractcontract: 'abstractcontract',
  program: 'program',
  contract: 'contract',
  functioninvocationresult: 'functioninvocationresult',
  functioninvocationscope: 'functioninvocationscope',
  instructionset: 'instructionset',
  invocationcallresult: 'invocationcallresult',
  invocationresult: 'invocationresult',
  invokefunction: 'invokefunction',
  invokefunctions: 'invokefunctions',
  multicallinvocationscope: 'multicallinvocationscope',
  scriptrequest: 'scriptrequest',
  script: 'script',
  utils: 'utils',
  datetime: 'datetime',
};

export function toCnLabel(label: string) {
  return labelMap[label.toLowerCase()] || label;
}
